# Generated by Django 4.1.3 on 2022-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tanlov', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
    ]
